# 👉 Goal:
### Teach a machine learning model to predict sentiment

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [5]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant" , 30)

[1, 21]

In [7]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews 

[[9, 20],
 [1, 21],
 [9, 7],
 [26, 15, 19],
 [22, 17, 1],
 [14, 20],
 [23, 17, 2],
 [4, 6],
 [4, 9],
 [20, 9]]

In [9]:
max_legth = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_legth,padding='post')
padded_reviews

array([[ 9, 20,  0],
       [ 1, 21,  0],
       [ 9,  7,  0],
       [26, 15, 19],
       [22, 17,  1],
       [14, 20,  0],
       [23, 17,  2],
       [ 4,  6,  0],
       [ 4,  9,  0],
       [20,  9,  0]])

In [10]:
embeded_vector_size= 5
model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_legth,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [13]:
x = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [16]:
model.fit(x,y,epochs=50,verbose=0)

In [17]:
loss , accuracy  = model.evaluate(x,y)
accuracy

1/1 [==============================] - 0s 335ms/step - loss: 0.6304 - accuracy: 0.9000


0.8999999761581421

In [18]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [19]:
weights[20] #food

array([ 0.04599986,  0.0059984 ,  0.00288293, -0.02021721,  0.08044839],
      dtype=float32)

In [20]:
weights[21]

array([-0.02150218,  0.08667541, -0.01696768,  0.10037504,  0.00110538],
      dtype=float32)